.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. mooncoin_qt test_mooncoin_qt
clean: FORCE
	$(MAKE) -C .. mooncoin_qt_clean test_mooncoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_mooncoin_qt_check
mooncoin-qt mooncoin-qt.exe: FORCE
	 $(MAKE) -C .. mooncoin_qt
